--- # ansible setup
- hosts: webserver
  user: ricky
  sudo: yes
  tasks:
  - name: installing httpd package
    yum: name=httpd state=installed
  - name: servive started httpd
    service: name=httpd state=started
